# Generated by Django 2.0.8 on 2020-05-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_server_idc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='idc',
        ),
    ]
