# Generated by Django 2.0.8 on 2020-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_remove_server_idc'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='server',
        #     name='Asset_number',
        #     field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='资产编号'),
        # ),
        # migrations.AddField(
        #     model_name='server',
        #     name='under_name',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='所属名下'),
        # ),
        # migrations.RemoveField(
        #     model_name='server',
        #     name='uuid',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='server',
        #     unique_together={('Asset_number', 'server_type')},
        # ),
    ]
