# Generated by Django 2.0.8 on 2020-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20200520_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='uuid'),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('uuid', 'server_type')},
        ),
    ]
