# Generated by Django 2.0.8 on 2020-05-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20200520_1817'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='server',
    #         name='under_name',
    #         field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='所属名下'),
    #     ),
    # ]
