# Generated by Django 2.0.8 on 2020-05-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_server_under_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='Asset_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='资产编号'),
        ),
    ]
