# Generated by Django 2.0.8 on 2020-05-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_server_asset_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='Asset_number',
            new_name='asset_number',
        ),
    ]
